services:
  postgres:
    image: postgres:17-alpine@sha256:b0f9560a2de083e2cc7382e75f808c7381a32852a7ec49117deedb300e552b24
    environment:
      POSTGRES_DB: tsundoku
      POSTGRES_USER: tsundoku
      POSTGRES_PASSWORD: tsundoku
    ports:
      - "5432:5432"
    volumes:
      - tsundoku_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tsundoku"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  tsundoku_pg_data:
