services:
  postgres:
    image: postgres:17-alpine@sha256:f02121de6f74d30d8a94cd1d9584125e2178d7e6c377d8130112d4e52d867995
    environment:
      POSTGRES_DB: tsundoku
      POSTGRES_USER: tsundoku
      POSTGRES_PASSWORD: tsundoku
    ports:
      - "5432:5432"
    volumes:
      - tsundoku_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tsundoku"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  tsundoku_pg_data:
